# _config.yml

# Site Info
title: Liam Chambers' Blog
author:
  name: Liam Chambers
  # avatar: /assets/liamsmediapfp1.jpg # Add an image named avatar.png to your assets folder
  bio: "Life Long Learning Documented."
  social:
 #   - name: YouTube
 #     url: https://www.youtube.com/@LiamChambers.
 #   - name: X
 #     url: https://x.com/LiamChambrs
    - name: LinkedIn
      url: https://www.linkedin.com/in/liamchambers/

# Theme
theme: jekyll-theme-minimal

# This is required for GitHub Pages
baseurl: "" # Keep this empty
url: "https://liamchambers9.github.io" # Don't forget to replace with your site's URL

# Add this new section
collections:
  projects:
    output: true

